name: Lint Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint Check
        run: bun run lint

      - name: Format Check
        run: bun run format:check
